Added lifecycle hook

diff --git a/components/mock/templates/wildfly_mock_setup.sh.tmpl b/components/mock/templates/wildfly_mock_setup.sh.tmpl
--- a/components/mock/templates/wildfly_mock_setup.sh.tmpl
+++ b/components/mock/templates/wildfly_mock_setup.sh.tmpl
@@ -1,8 +1,76 @@
-#!/bin/bash -xe
+#!/bin/bash -x
 
 function log() {
   echo "[$(date)]$1" | tee -a /var/log/wildfly_mock_cloudinit.log
 }
+
+function json_escape () {
+    printf '%s' "$1" | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
+}
+
+BOOTSTRAP_SUCCESS=1
+rm -f  /var/log/cloud-init.log
+export aws="$(which aws || echo '/usr/bin/aws')";
+export curl="$(which curl || echo '/usr/bin/curl')";
+
+# Instance ID begets all things...
+log 'INFO' 'Retrieving Instance ID from Metadata';
+instance_id="$($${curl} -s http://169.254.169.254/latest/meta-data/instance-id)";
+if [ $${?} -ne 0 ]; then
+  error "Failed to retrieve Instance ID";
+  BOOTSTRAP_SUCCESS=0
+fi
+log 'INFO' "Instance ID: $${instance_id}";
+
+# Get Current AWS Region in order to do anything useful...
+log 'INFO' 'Retrieving Instance Identity Document from Metadata';
+instance_identity_document="$($${curl} -s http://169.254.169.254/latest/dynamic/instance-identity/document)";
+if [ $${?} -ne 0 ]; then
+  BOOTSTRAP_SUCCESS=0
+  error "$${curl} -s http://169.254.169.254/latest/dynamic/instance-identity/document";
+else
+  log 'INFO' 'Instance Identity Document Retrieved';
+
+  region="$(echo "$${instance_identity_document}" | jq -r .region)";
+
+  if [ $${?} -ne 0 ]; then
+    BOOTSTRAP_SUCCESS=0
+    error 'jq: Instance Identity Document could not be parsed for current Region';
+  else
+    log 'INFO' "Region retrieved: $${region}";
+  fi;
+
+  # Make it available to the AWS cli; who needs to specify the region manually on every single call(?)
+  export AWS_DEFAULT_REGION="$${region}";
+fi;
+
+# Get the Autoscaling Group Name - it's a bit dirty but it works.
+asg_name="$($${aws} autoscaling describe-auto-scaling-instances \
+  --instance "$${instance_id}" \
+  --output json \
+  | jq -r .AutoScalingInstances[0].AutoScalingGroupName)";
+
+if [ $${?} -ne 0 ]; then
+  error 'Failed to retrieve the autoscaling group name for this instance';
+  BOOTSTRAP_SUCCESS=0
+else
+  log 'INFO' "ASG name retrieved: $${asg_name}";
+fi;
+
+# Get the Launching LifeCycle Hook Name for this ASG (Making the assumption there's only one hook!)
+lifecycle_hook_name="$($${aws} autoscaling describe-lifecycle-hooks \
+  --auto-scaling-group-name "$${asg_name}" \
+  --output json \
+  | jq -r '.LifecycleHooks[] | select(.LifecycleTransition=="autoscaling:EC2_INSTANCE_LAUNCHING") | .LifecycleHookName')";
+
+if [ $${?} -ne 0 ]; then
+  error "Failed to retrieve lifecycle hook name for the autoscaling:EC2_INSTANCE_LAUNCHING transition for the autoscaling group named: $${asg_name}";
+  BOOTSTRAP_SUCCESS=0
+else
+  log 'INFO' "Lifecycle hook name retrieved: $${lifecycle_hook_name}"
+fi;
+
+# Prerequisite information gathered - begin bootstrapping
 
 log '[INFO] Running puppet to configure wildfly environment'
 
@@ -13,16 +81,47 @@ facts_path="/opt/puppetlabs/facter/facts.d"
 echo -n 'environment: ${ENVIRONMENT}'    > "$${facts_path}/environment.yaml"
 echo -n 'nodetype: ${NODETYPE}'          > "$${facts_path}/nodetype.yaml"
 echo -n 'aws_account: ${AWS_ACCOUNT_ID}' > "$${facts_path}/aws_account.yaml"
+echo
 
 cd /opt/packer-puppet-masterless
 
 # TODO: peacheym: Convert this script to use standardised
 # error handling, remove the "set -e" and then
 # add --detailed-exitcodes and handle the return codes puppet provides
+
 /opt/puppetlabs/bin/puppet apply \
   --verbose \
   --modulepath='/opt/packer-puppet-masterless/module-0:/opt/packer-puppet-masterless/module-1' \
   --hiera_config='/opt/packer-puppet-masterless/hiera.yaml' \
   /opt/packer-puppet-masterless/manifests/site.pp
 
-log '[INFO] Wildfly mock configuration finished'
+case $${?} in
+  6|4|1)
+    log "ERROR" "Puppet run failed with exit code $${?}"
+    BOOTSTRAP_SUCCESS=0 ;;
+  *)
+    log "INFO" "Puppet run completed" ;;
+esac
+
+
+if [ $${BOOTSTRAP_SUCCESS} = 1 ]; then
+  log "SUCCESS" "Bootstrap completed for nodetype: ${NODETYPE}"
+else
+  log "ERROR" "Bootstrap abandoned for nodetype: ${NODETYPE}"
+fi
+
+if [ $${BOOTSTRAP_SUCCESS} = 1 ]; then
+  aws autoscaling complete-lifecycle-action \
+      --lifecycle-action-result CONTINUE \
+      --instance-id "$${instance_id}" \
+      --lifecycle-hook-name "$${lifecycle_hook_name}" \
+      --auto-scaling-group-name "$${asg_name}" \
+      || error 'Failed to complete lifecycle hook';
+else
+  aws autoscaling complete-lifecycle-action \
+    --lifecycle-action-result ABANDON \
+    --instance-id "$${instance_id}" \
+    --lifecycle-hook-name "$${lifecycle_hook_name}" \
+    --auto-scaling-group-name "$${asg_name}" \
+    || error 'Failed to complete lifecycle hook';
+fi
