Fix everything

diff --git a/components/mock/templates/wildfly_mock_setup.sh.tmpl b/components/mock/templates/wildfly_mock_setup.sh.tmpl
--- a/components/mock/templates/wildfly_mock_setup.sh.tmpl
+++ b/components/mock/templates/wildfly_mock_setup.sh.tmpl
@@ -6,15 +6,20 @@ function log() {
 
 log '[INFO] Running puppet to configure wildfly environment'
 
-
 sed -E -i "s/'[a-z0-9]{8}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-f0-9]{4}\-[a-z0-9]{12}'/'${kms_key}'/g" /etc/eyaml/config.yaml
-
 
 cd /tmp/packer-puppet-masterless
 export FACTER_environment='${environment}'
-export FACTER_puppet_environment='${puppet_environment}'
 export FACTER_nodetype='${nodetype}'
 export FACTER_aws_account='${aws_account_id}'
-/opt/puppetlabs/bin/puppet apply --verbose --modulepath='/tmp/packer-puppet-masterless/module-0:/tmp/packer-puppet-masterless/module-1' --hiera_config='/tmp/packer-puppet-masterless/hiera.yaml' --detailed-exitcodes /tmp/packer-puppet-masterless/manifests/site.pp
+
+# TODO: peacheym: Convert this script to use standardised
+# error handling, remove the "set -e" and then
+# add --detailed-exitcodes and handle the return codes puppet provides
+/opt/puppetlabs/bin/puppet apply \
+  --verbose \
+  --modulepath='/tmp/packer-puppet-masterless/module-0:/tmp/packer-puppet-masterless/module-1' \
+  --hiera_config='/tmp/packer-puppet-masterless/hiera.yaml' \
+  /tmp/packer-puppet-masterless/manifests/site.pp
 
 log '[INFO] Wildfly mock configuration finished'
diff --git a/components/tars-batch/templates/wildfly_batch_setup.sh.tmpl b/components/tars-batch/templates/wildfly_batch_setup.sh.tmpl
--- a/components/tars-batch/templates/wildfly_batch_setup.sh.tmpl
+++ b/components/tars-batch/templates/wildfly_batch_setup.sh.tmpl
@@ -6,7 +6,6 @@ function log() {
 
 log '[INFO] Running puppet to configure wildfly environment'
 
-
 sed -E -i "s/'[a-z0-9]{8}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-f0-9]{4}\-[a-z0-9]{12}'/'${kms_key}'/g" /etc/eyaml/config.yaml
 
 # Ensure the directory exists
@@ -16,6 +15,7 @@ mkdir -p /efs;
 export region="$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)";
 export az="$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)";
 
+# TODO: peacheym: Migrate to the AZ-independent URL
 # Set mount information in /etc/fstab - we're unlikely to reboot, but it can't hurt to ensure it remains
 echo "$${az}.${EFS_ID}.efs.$${region}.amazonaws.com:/ /efs nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0" >> /etc/fstab
 
@@ -24,10 +24,17 @@ mount /efs
 
 cd /tmp/packer-puppet-masterless
 export FACTER_environment='${environment}'
-export FACTER_puppet_environment='${puppet_environment}'
 export FACTER_nodetype='${nodetype}'
 export FACTER_aws_account='${aws_account_id}'
-/opt/puppetlabs/bin/puppet apply --verbose --modulepath='/tmp/packer-puppet-masterless/module-0:/tmp/packer-puppet-masterless/module-1' --hiera_config='/tmp/packer-puppet-masterless/hiera.yaml'  /tmp/packer-puppet-masterless/manifests/site.pp
+
+# TODO: peacheym: Convert this script to use standardised
+# error handling, remove the "set -e" and then
+# add --detailed-exitcodes and handle the return codes puppet provides
+/opt/puppetlabs/bin/puppet apply \
+  --verbose \
+  --modulepath='/tmp/packer-puppet-masterless/module-0:/tmp/packer-puppet-masterless/module-1' \
+  --hiera_config='/tmp/packer-puppet-masterless/hiera.yaml' \
+  /tmp/packer-puppet-masterless/manifests/site.pp
 
 # Now puppet has finished and we don't need to lookup KMS keys, we can override DNS
 # Override DNS to use DVSA Azure DNS. TF knows what the IP's are so lets do it here, rather than puppet
@@ -38,6 +45,5 @@ for server in $$servers
 do
   echo "nameserver $${server}" >> /etc/resolv.conf
 done
-
 
 log '[INFO] Wildfly batch configuration finished'
